language: node_js
node_js:
  - "10"
  - "12"
  - "13"
install:
  - npm install
script:
  - npm run cover:check
branches:
  only:
  - master
  - develop
# Node 6 doesn't run prepare after install:
before_script: "npm run build"
# Send test coverage data to Coveralls:
after_script: "npm run coveralls"
